---
- name: Install Murmur (debian family)
  when: ansible_os_family == 'Debian'
  apt: name=mumble-server state=latest

- name: Install Murmur (not debian family)
  when: ansible_os_family != 'Debian'
  package: name=murmur state=latest

- name: Generate the Murmur config file
  template: src=mumble-server.ini.j2
            dest=/etc/mumble-server.ini
            owner=root
            group=mumble-server
            mode=640
  notify: Restart Murmur
