---
- name: Install the python-software-properties utility
  package: name=python-software-properties state=latest

- name: Add the PPA
  when: ansible_distribution == 'Ubuntu'
  apt_repository: repo='ppa:mumble/release'

- name: Install Murmur (debian family)
  when: ansible_os_family == 'Debian'
  package: name=mumble-server state=latest

- name: Install Murmur (not debian family)
  when: ansible_os_family != 'Debian'
  package: name=murmur state=latest

- name: Generate the Murmur config file
  template: src=mumble-server.ini.j2
            dest=/etc/mumble-server.ini
            owner=root
            group=mumble-server
            mode=640
  notify: Restart Murmur
